baseURL = 'https://derlev.xyz/'
languageCode = 'en-us'
title = 'DerLev'

disableKinds = ["RSS"]
disableHugoGeneratorInject = true
enableRobotsTXT = true

[sitemap]
  changeFreq = 'weekly'
  priority = 1

[taxonomies]
  tag = 'tags'

[markup.goldmark.renderer]
  unsafe = true
