baseURL = 'https://derlev.xyz/'
languageCode = 'en-us'
title = 'DerLev'
copyright = 'DerLev'
timezone = 'Europe/Berlin'

disableKinds = ["RSS"]
disableHugoGeneratorInject = true
enableRobotsTXT = true

enableEmoji = true
enableGitInfo = true

[mediaTypes]
  [mediaTypes."text/droplist"]
    suffixes = ["droplist"]

[outputFormats.droplist]
  mediatype = "text/droplist"
  isPlainText = true

[outputs]
  page = ["HTML", "droplist"]

[permalinks]
  [permalinks.page]
    blog = "/blog/:year/:slugorfilename"

[sitemap]
  changeFreq = 'weekly'
  priority = 1

[taxonomies]
  tag = 'tags'
  author = 'authors'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 2

[minify]
  minifyOutput = true

  [minify.tdewolff.html]
    keepQuotes = true
